// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyfimmnlevvtrjfbzfpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZmltbW5sZXZ2dHJqZmJ6ZnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODExNjgsImV4cCI6MjA2MDA1NzE2OH0.4yPZGadH9fcDiMMgXZ28kdTBzEIjHqx5nu6sw8n9zSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);